# Generated by Django 3.1.1 on 2020-09-18 08:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=150, null=True, verbose_name='Film ismi')),
                ('movie_content', ckeditor.fields.RichTextField(max_length=2000, null=True, verbose_name='Film açıklama ')),
                ('release_date', models.DateField(null=True, verbose_name='Film çıkış tarihi')),
                ('imdb_reyting', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images', verbose_name='Fotoğraf')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturma tarihi')),
                ('created', models.BooleanField(default=True, null=True, verbose_name='Film yayındamı')),
                ('runtime', models.CharField(max_length=50, null=True, verbose_name='film Süresi')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ManyToManyField(related_name='Movie', to='movie.Category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmler',
            },
        ),
    ]
