# Generated by Django 3.1.1 on 2020-09-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=75, verbose_name='Film ismi')),
                ('movie_content', models.TextField(max_length=600, verbose_name='Film açıklama ')),
                ('release_date', models.DateField(verbose_name='Film çıkış tarihi')),
                ('imdb_reyting', models.CharField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Fotoğraf')),
                ('oluşturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma tarihi')),
                ('created', models.BooleanField(default=True, null=True, verbose_name='Film yayındamı')),
                ('category', models.ManyToManyField(blank=True, null=True, to='movie.Category')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmler',
            },
        ),
    ]
