# Generated by Django 3.1.1 on 2020-09-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_reyting',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_content',
            field=models.TextField(max_length=600, null=True, verbose_name='Film açıklama '),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=75, null=True, verbose_name='Film ismi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='oluşturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturma tarihi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Film çıkış tarihi'),
        ),
    ]
