# Generated by Django 3.1.1 on 2020-09-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=1000, null=True, verbose_name='Film Url'),
        ),
    ]
