# Generated by Django 2.2.12 on 2020-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200923_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(null=True, upload_to='static/images/Actor', verbose_name='Aktör Fotoğrafı'),
        ),
    ]
