# Generated by Django 3.1.1 on 2020-09-04 11:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200903_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='oluşturma_tarihi',
            new_name='publishing_date',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_content',
            field=ckeditor.fields.RichTextField(max_length=2000, null=True, verbose_name='Film açıklama '),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Film ismi'),
        ),
    ]
