# Generated by Django 3.1.1 on 2020-09-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200904_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=50, null=True, verbose_name='film Süresi'),
        ),
    ]
