# Generated by Django 2.2.12 on 2020-09-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200925_1552'),
        ('movie', '0002_movie_url'),
    ]

    operations = [
    ]
