# Generated by Django 2.2.12 on 2020-09-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200928_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Adı')),
                ('surname', models.CharField(max_length=150, null=True, verbose_name='Soyadı')),
                ('mail', models.CharField(max_length=150, null=True, verbose_name='Mail')),
                ('comment', models.TextField(max_length=250, null=True, verbose_name='Yorum')),
                ('movie', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Yorumlar',
            },
        ),
    ]
