# Generated by Django 3.1.1 on 2020-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200915_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='Aylakbakkal',
            field=models.ManyToManyField(related_name='Movie', to='movie.Category', verbose_name='Kategori'),
        ),
    ]
