# Generated by Django 3.1.1 on 2020-09-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200916_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Aylakbakkal',
            new_name='Category',
        ),
    ]
